### ISSUE TITLE
Setup prettier

### ISSUE THREAD

**Issue by TotomInc** [TotomInc/loaderz#9]
Prettier is an opinionated code formatter which keep a constant code-format and can be run into the tests.

**Comment by aljones15** [comment]
you want in a pre-commit hook or before the tests run?

**Comment by TotomInc** [comment]
Ideally a pre-commit hook would be better.

**Comment by aljones15** [comment]
lol I did that then say you had a branch hold on a second I will put in a p.r. in a moment

**Comment by TotomInc** [comment]
Yep I just added husky and prettier on dev-deps, haven't done something really big on this branch.

**Comment by aljones15** [comment]
ok added it to the precommit step along with your tests passes travis pr is in. I need to get back to work.
